services:
  - name: "My Pages"
    endpoints:
      - url: "https://cctvlog.com"
      - url: "https://bing.cctvlog.com"
      - url: "https://ip.cctvlog.com"
      - url: "https://threejs-3d.cctvlog.com"
  - name: "My Services"
    endpoints:
      - url: "https://jb.cctvlog.com"
      - url: "https://nav.cctvlog.com"
